name: PrisonFoundations
main: JeNDS.Plugins.PrisonFundations.Main
api-version: 1.16
version: 3.2
author: JeNDS
description: -no desc-
softdepend: [ PlaceholderAPI,Multiverse-Core ]
load: POSTWORLD
depend:
  - Vault
  - JeNDSAPI
commands:
  rank:
    description: 'Command to Rankup'
  ranks:
    description: 'Command to Rankup'
  rankup:
    description: 'Command to Rankup'
  prices:
    description: 'Command for shop prices'
  sell:
    description: 'Command to sell'
  autosell:
    description: 'Command to autosell'
  pf:
    description: 'Main game command'